### ISSUE TITLE
Git Cloner Fatal: destination path '/code' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by jasperf** [smart48/smt-deploy#13]
Cloning of the repository

```yaml
# Laravel Code Download so we can run Horizon without issues 
# and have a codebase to start with For private repo better to add 
# code to laravel image
# initContainers:
  - name: git-cloner
    image: alpine/git
    imagePullPolicy: IfNotPresent
    args:
        - clone
        - --single-branch
        - --
        - https://github.com/smart48/smt-demo
        - /code
    volumeMounts:
    - mountPath: /code
      name: code-storage
```
 fails

```
kubectl logs -f app-6b8877cdd7-b74hb git-cloner     
fatal: destination path '/code' already exists and is not an empty directory.
```

When I ssh into the kube I see

```
$ cd /data/code/
$ ll
-bash: ll: command not found
$ ls -la
total 8
drwxr-xr-x 2 root root 4096 Dec  7 04:50 .
drwxr-xr-x 5 root root 4096 Dec  7 04:50 ..
```

which is ...odd
