### ISSUE TITLE
Workspace port 2222 Local / DO

### ISSUE THREAD

**Issue by jasperf** [smart48/smt-deploy#3]
As discussed [workspace container](https://github.com/smart48/smt-workspace) should be accessible from the outside so a service has been added. But it needs to allow `ssh forge@domain.nl` and deploy using PHP Deployer. So we probably need to use port 2222 in Deployer to send it to port 22 on workspace container instead of Droplet. See https://github.com/deployphp/deployer/issues/1636#issuecomment-567115561

**Comment by jasperf** [comment]
Just saw we do have

```yaml
ports:
    - protocol: TCP
      port: 2222
      # targetport is the internal port where traffic is sent to
      targetPort: 22
```

in the workspace service so perhaps that is okay already. Just need to see that workspace can communicate with the laravel php image and or php worker.
